/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'created' : Time,
  'content' : string,
  'author' : string,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'created' : Time,
  'content' : string,
  'category' : NoteCategory,
}
export type NoteCategory = { 'adhd' : null } |
  { 'dyslexia' : null } |
  { 'autism' : null } |
  { 'general' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YouTubeVideo {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'description' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlog' : ActorMethod<[string, string, string], BlogPost>,
  'createNote' : ActorMethod<[string, string, NoteCategory], Note>,
  'createVideo' : ActorMethod<[string, string, string], YouTubeVideo>,
  'deleteBlog' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'getAllBlogs' : ActorMethod<[], Array<BlogPost>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllVideos' : ActorMethod<[], Array<YouTubeVideo>>,
  'getBlog' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNotesByCategory' : ActorMethod<[NoteCategory], Array<Note>>,
  'getVideo' : ActorMethod<[bigint], [] | [YouTubeVideo]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateBlog' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateNote' : ActorMethod<[bigint, string, string, NoteCategory], undefined>,
  'updateVideo' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];