/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'created' : Time,
  'content' : IDL.Text,
  'author' : IDL.Text,
});
export const NoteCategory = IDL.Variant({
  'adhd' : IDL.Null,
  'dyslexia' : IDL.Null,
  'autism' : IDL.Null,
  'general' : IDL.Null,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'created' : Time,
  'content' : IDL.Text,
  'category' : NoteCategory,
});
export const YouTubeVideo = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlog' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BlogPost], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, NoteCategory], [Note], []),
  'createVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [YouTubeVideo], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], ['query']),
  'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNotesByCategory' : IDL.Func([NoteCategory], [IDL.Vec(Note)], ['query']),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(YouTubeVideo)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateBlog' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, NoteCategory], [], []),
  'updateVideo' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'created' : Time,
    'content' : IDL.Text,
    'author' : IDL.Text,
  });
  const NoteCategory = IDL.Variant({
    'adhd' : IDL.Null,
    'dyslexia' : IDL.Null,
    'autism' : IDL.Null,
    'general' : IDL.Null,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'created' : Time,
    'content' : IDL.Text,
    'category' : NoteCategory,
  });
  const YouTubeVideo = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlog' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BlogPost], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, NoteCategory], [Note], []),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [YouTubeVideo],
        [],
      ),
    'deleteBlog' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], ['query']),
    'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNotesByCategory' : IDL.Func([NoteCategory], [IDL.Vec(Note)], ['query']),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(YouTubeVideo)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateBlog' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, NoteCategory],
        [],
        [],
      ),
    'updateVideo' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };